steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'github.com/findrandomevents/eventdb/cmd/eventdb']
  env: ['PROJECT_ROOT=github.com/findrandomevents/eventdb']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/eventdb:$COMMIT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/eventdb:$COMMIT_SHA']
